### ISSUE TITLE
Tinymce Plugin does not function with Andreas225

### ISSUE THREAD

**Issue by catflinger** [fifteensquared/fifteensquared-theme#12]
The original comment field shows.

**Comment by catflinger** [comment]
This has been temporarily fixed in 1.0.2 by removing comments.p.p from the theme.  

More investigation is needed to determine what other effects this might have.

**Comment by catflinger** [comment]
(pp Geoff) Large blank area showing before WSYWIG comment entry on sandbox.fifteensquared.org

**Comment by catflinger** [comment]
Sandbox currently installed at 1.0.0.  Update to 1.0.2 and try again.

**Comment by Walahfrid** [comment]
Sandbox updated to 1.0.2. Large blank area still appearing above the WYSIWYG comment field on short posts (only a few lines of text in the content). No blank space on longer posts.

**Comment by catflinger** [comment]
Sandbox has possible fix loaded.  A brief test suggests it functions OK, tiny MCEeditor shows and adds comments. Mobile view shows without wysiwyg.

If this looks OK I will create a new release if and when we decide to put it live.

**Comment by Walahfrid** [comment]
Sandbox updated to fifteensquared-plugin v1.0.1.

The WYSIWYG editor seems to be fine in desktop view but I cannot test it in the IE11 phone emulator because the mobile view is no longer activated (the same thing happened with your new, stripped-down theme).  The emulator works correctly on the live site so perhaps a clash between the new comments.php and the WPtouch plugin? There were no mobile view issues when comments.php was simply deleted.

**Comment by catflinger** [comment]
I can use mobile site on my physical phone (Andorid Nougat), no problems at all that I can see.
I will try it on my wife's Windows phone when she gets home later this evening.

**Comment by catflinger** [comment]
Feel free to investigate any theories you have why it isn't working on your emulator.

**Comment by catflinger** [comment]
At 8.05am 17th Dec sandbox: WPTouch and TinyMce seem to work fine from Lumia 865 running Windows 10 Mobile and Edge.

**Comment by Walahfrid** [comment]
This appears to be an IE11 emulator issue (but affected by comments.php).
The IE11 emulator displays as follows:
andreas09 - mobile view
andreas255 (original comments.php) - mobile view
andreas225 (no comments.php) - mobile view
andreas225 (modified comments.php) - desktop view
new stripped down theme - desktop view
live site - mobile view

However, the Edge phone emulator gives the mobile view for andreas225 (modified comments.php), unlike IE11.
Next I will see what happens in the Chrome emulator.

**Comment by catflinger** [comment]
I may have been misunderstandng you.  When you said the mobile view didn't display did you mean that it failed to load at all or that you got the desktop view instead?

I always understood that you meant it failed completely, but I now think you meant it displays the desktop editor instead.  Is that right?

**Comment by Walahfrid** [comment]
Sorry for any confusion, in the emulator the site appears but, as indicated above, not with the correct view.

I have now tried the Chrome phone emulator. Every option gave the same result with andreas225 (modified comments.php), desktop view instead of mobile.

I then tried the IE11 emulator using my laptop and this displayed andreas225 (modified comments.php) correctly - mobile view, The laptop has IE11.0.47 and my desktop IE11.0.48. Obviously there was some change in the latest update (which is awaiting installation on my laptop).

**Comment by catflinger** [comment]
Strange.  I can't think of any reason why displaying the comments would affect how the server determines the device type.

I do know that determining the device type is a bit of a black art and not very reliable.

**Comment by catflinger** [comment]
I just had a quick go using Chrome.  The sandbox Andreas225 loaded and a quick look via FTP showed the comments.php as 88 bytes long, which looks like the newest version.

Both the desktop and mobile views displayed correctly.  It switches between mobile and desktop sites whenever I toggle the device type.

**Comment by Walahfrid** [comment]
Thanks Paul
Chrome on my laptop has just updated itself from v62 to v63 so I rechecked the sandbox using the emulator. This time, unlike before the update, I did get the mobile view. It will be interesting to see how my laptop performs when IE11 is eventually updated (it's been downloading the latest Windows updates for the last 2 hours and it still only 20% of the way through).

I will do some more testing this evening using the Chrome and Edge emulators and if all goes well we might be in a position to add this plugin to the live site.

**Comment by Walahfrid** [comment]
IE11 now updated on laptop. The emulator displays the correct mobile view. So why the difference between laptop and desktop?
Desktop running Win 10 Pro, laptop has Win 10 Home. Parts of IE11 differ despite having the same version number.
For example 'user agent string' options in the laptop IE11 emulator include Window Phone 10 whereas in the desktop IE11 emulator this has been replaced with Edge and Edge - Windows 10 Mobile.

**Comment by Walahfrid** [comment]
Emulator testing of plugin completed. No issues found. No debug.log entries If you are happy with what you've found on real phones then it looks like the plugin can be added to the live site.

Now that this plugin works correctly, I don't think it's worth considering the alternative that I mentioned in a email earlier today. I don't like the way the buttons insert the HTML codes into the comment that is being typed (though the preview is WYSIWYG, at least for the embellishments I tried).

Of more concern is the fact that we do not know if it will work in the mobile view generated by WPtouch and we don't know if the plugin can be turned off for mobile if it doesn't. These things could be tested (if I manage to find out which plugin it is) but I think we have spent enough time as it is in getting a WYSIWYG comment editor to work satisfactorily.

**Comment by catflinger** [comment]
I will make another release of wp-andreas225.

We should clean up the sandbox, install the new release and give it a thorough test.

**Comment by catflinger** [comment]
Release 1.0.3 in GitHub now ready to test.

**Comment by catflinger** [comment]
The release is good to go, but I am still mystified as to what was going on here.

Can you think of any reason why the IE11 emulator was not showing the mobile view?  I can't think of any reason at all why just removing comemnts.php would have any effect on which site was shown.  Can you think of any side effect that might have caused it?  For example, did you switch between two themes during the test (one with, one without comments.php) or did you just remove comments.php manually?  

Was the removal of comments.php from a folder absolutely the only change of any sort that could have happened between seeing the desktop and mobile view?

**Comment by Walahfrid** [comment]
I will be installing release 1.0.3 in the sandbox shortly.

All the tests I did yesterday were carried out with no change to v1.0.2 in the sandbox. I updated the fifteensquared plugin to 1.0.1 before doing any tests.

My comments relating to the mobile views of earlier versions were taken from notes that I made at the time when they had been installed in the sandbox.

I too am baffled and cannot come up with a reason for what I have seen over the last few days. One thing that did surprise me was that the emulator in the Windows Pro version of IE11 differs from that in the Windows Home version, despite them both having the same version release number.

Prior to yesterday I had only used the Pro version of the IE11 emulator so I don't know what the Home version or Chrome would have displayed for the earlier versions of andreas225 and andreas09. When you originally suggested removing comments.php because that seemed to be a way of getting the editor plugin to work, so far as I can remember that was the only change I made to the sandbox apart from reactivating the editor plugin to check that it was working.

**Comment by Walahfrid** [comment]
Release 1.0.3 now installed in the sandbox.

**Comment by catflinger** [comment]
I updated my laptop form Windows 10 Home to Windows 10 Pro recently.  A bunch of stuff didn't work very well until Windows update had run a few times.  Then the problems went away.  I think Pro must get a different updates than Home.

I think we will have to leave the Windows Emulator thing unexplained.  I am reluctant to conclude that there is a direct causal link between removing a file like comments.php and the server inferring a different device type for a client.  I think there must be a side effect somewhere but I have no idea what it might be.

**Comment by Walahfrid** [comment]
I have had Windows 10 Pro since it was first released (migrated from Windows 7 Business) so it has had many updates.

This issue has been bugging me all day (pardon the pun) and I thought I might have found the reason -  IE11 Pro emulation having a user agent that isn't supported by WPtouch - so I did some more tests and found that isn't the cause.

IE11 Home emulator - live site - mobile view
IE11 Pro emulator - live site - mobile view
IE11 Home emulator - dashboard - mobile view
IE11 Pro emularor - dashboard - desktop view

So, what are the differences between the live site and the dashboard? The dashboard has a different comments.php, the two plugins that generate the WYSIWYG comment editor and an earlier version of the fifteensquared plugin.

I deactivated the three plugins and temporarily removed comments.php. Still desktop view in the IE11 Pro emulator. I then reactivated the fifteensquared plugin and checked again. No change. I reactivated the comment editor plugs. Again no change. Finally I reinstated comments.php. Still desktop view in the Pro emulator.

There is a possibility that I was testing andreas225 v1.0.0 (with and without comments.php) before the latest Windows update, which might account for why I could get the mobile view in the Pro emulator then but not now, but I can't be certain.

Before moving on to testing release 1.0.3 I am going to repeat the mobile view checks that I did yesterday using the IE11 Home and Chrome emulators, just for some peace of mind.

**Comment by Walahfrid** [comment]
I have rechecked the live site and sandbox using the emulators in IE11 Home, IE11 Pro, Chrome and Edge. The only time that I didn't get the correct mobile view was when viewing the sandbox using the IE11 Pro emulator which retained the desktop view no matter what configurations I tried in the emulator. The cause of this remains a mystery.

**Comment by Walahfrid** [comment]
I have tested the andreas225 v1.0.3 release in the sandbox and all appears fine, including the WYSIWYG comment editor, except for one navigation error, namely the link to comments in the footer of each post displayed on the home page and the various archive pages.

If there are no comments, clicking on the link adds /#respond to the post URL and it is acted upon, the post is displayed already scrolled down to the comment editor field/

If there are comments, clicking the link adds /#comments to the post URL but it is not acted upon, the post is displayed but there is no automatic scroll down, this has to be done manually to get to the start of the comments.

The live site does this correctly and clicking on the comments link takes you directly to either the comment editor field (no comments) or the start of the comment list (with comments).

**Comment by catflinger** [comment]
Fix for missing #comments anchor in release 1.0.4.

**Comment by Walahfrid** [comment]
v1.0.4 installed in sandbox. #comments anchor working but this has highlighted that there is something missing. Between the post footer and the start of the comments there should be a line:

xx Responses to "post-title"

On the live site the #comments anchor scrolls to this line. This line may have been missing before and I failed to notice the omission because the comments link wasn't working.

I will shortly carry out a side-by-side check of the sandbox and live sites to make sure that there isn't anything else that I have missed.

**Comment by Walahfrid** [comment]
Side-by-side check completed. I did not find other omissions in v1.0.4.

**Comment by catflinger** [comment]
moves responses count to a new issue

**Comment by catflinger** [comment]
Closing as main issue is resolved and related issues now raised their own threads.
