### ISSUE TITLE
Blank Space above comments replay on short posts

### ISSUE THREAD

**Issue by catflinger** [fifteensquared/fifteensquared-theme#17]
A large blank space displays above the reply section on short posts.

Occurs on live 
system 
desktop view
wp-andreas225 v1.0.5

**Comment by catflinger** [comment]
As a short term workaround try adding following to the site CSS via the admin panel style editor

```
div#respond.comment-respond {
    overflow: hidden;
}
```

**Comment by Walahfrid** [comment]
I've just checked an old short post on the live site - no gap between 'Leave a reply' and the comment editor field.
I created a new short test post - again no gap.
I haven't changed anything on the live site since yesterday afternoon so cannot explain why there was the gap when I posted the short announcement yesterday but not when I added a short test post today.

**Comment by catflinger** [comment]
I wonder if this might be down to various caches gradually being refreshed, it might just take time for everything to get back in sync.  We could just live with this for a few days and see if it sorts itself out.

**Comment by Walahfrid** [comment]
I am happy for this issue to be closed. I have been unable to get it to repeat today and I am the only one likely to publish a short post. If there is a similar problem in the future I will open a new issue for it.

**Comment by catflinger** [comment]
closing
